name: Dast Release

on:
  push:
    branches:
      - Dastrdly
     

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    
        

steps:
  - name: Run Dastardly Action Step
    uses: PortSwigger/dastardly-github-action@main
    with:
      target-url: 'https://ginandjuice.shop'
